### ISSUE TITLE
Allow PDFs to be opened directly in browser

### ISSUE THREAD

**Issue by copelco** [deardurham/dear-petition#12]
Add option to allow PDFs to be opened in the browser, rather than as an attachment.

**Comment by copelco** [comment]
@georgehelman This is now on staging. Does it work for you on your Windows machine?

**Comment by georgehelman** [comment]
This still doesn't work for me. Neither checkbox is checked in the download. If I save that download as a non-readable PDF, then both checkboxes are checked.

**Comment by copelco** [comment]
Interesting - even when viewing it in Chrome w/o downloading the PDF as an attachment (what this issue implements)? 

Bummer :( I opened #20 for the checkbox-specific issue.
