### ISSUE TITLE
Configure (and document) how to develop React app against different backends

### ISSUE THREAD

**Issue by copelco** [deardurham/dear-petition#127]
The React SPA is very simple to get running after cloning the repo:

```sh
npm i
npm run start
```

Ideally a frontend developer could point the backend API based on what was being developed:

1. To staging (maybe the default?)
2. To the Django docker container

This can be customized in ``package.json`` under the proxy setting:

```json
{
  "proxy": "http://localhost:8000/"
}
```

AC:
* Determine best way to override proxy
* README is updated with how to configure

**Comment by robert-w-gries** [comment]
I can pick this up and add other misc info to the Readme. Regarding the current default proxy, `http://django:8000`, is that a functional proxy? I haven't been able to get that working, only `localhost:8000` and the staging url work.
