### ISSUE TITLE
Add x button to close generate petition modal

### ISSUE THREAD

**Issue by copelco** [deardurham/dear-petition#148]
After clicking on a petition a modal is displayed to add agencies. Currently, the ESC key can be used to close the modal, but it's not intuitive. Ideally an x icon that's clickable could be used to close the modal.

AC:
* Update [GeneratePetitionModal](https://github.com/deardurham/dear-petition/blob/master/src/components/pages/GenerationPage/GeneratePetitionModal/GeneratePetitionModal.js) to include an x icon to call ``closeModal``

**Comment by robert-w-gries** [comment]
I can pick this up
