### ISSUE TITLE
Petition should not have 'INFRACTION' type

### ISSUE THREAD

**Issue by georgehelman** [deardurham/dear-petition#154]
Jessica showed us an example of an AOC-CR-287 that displayed a court record with a severity of 'INFRACTION'. We don't want infractions to show up on AOC-CR-287.

**Comment by copelco** [comment]
Do we remember which record had the infraction on it?

**Comment by jmluong** [comment]
the offending infraction is “failure to stop for stop sign” or similar. it should be on vernona yarboro, and possibly marcus corona.

Jessica M. Luong
Staff Attorney
Legal Aid of North Carolina, Inc.
PO Box 2101
Durham, NC 27702
p: 984-297-1981 | f: 919-682-8157
jessical@legalaidnc.org
________________________________

**Comment by jjohnson-ocs** [comment]
Can confirm FAIL STOP STOPSIGN/FLSH RED LT is on the Corona, Marcus Anthony record.

**Comment by jjohnson-ocs** [comment]
But actually the FAIL STOP SIGN isn't coming out on the petition.  However, EXCEEDING SAFE SPEED is coming out on the Randolph county petition.

**Comment by copelco** [comment]
Looks like infractions are identifiable in the record number:

![image](https://user-images.githubusercontent.com/129679/95751612-e00ece00-0c6c-11eb-8906-1e5a7d23bda4.png)

From: https://www.nccourts.gov/assets/documents/publications/ACIS_Inquiry_RG.pdf
