### ISSUE TITLE
Form 287 - Check mark in checkbox 3b

### ISSUE THREAD

**Issue by georgehelman** [deardurham/dear-petition#180]
287, box 3B, “charged with multiple offenses, and while some charges were dismissed, others resulted in conviction” - when tool sees guilty to lesser, to pick up the charge from ciprs that says convicted

Eg. person charged with larceny, plea would be “guilty to lesser”, charge would be guilty and that should go into box 3B. New form also requires listing of remaining guilty charge.

**Comment by georgehelman** [comment]
![check3b](https://user-images.githubusercontent.com/43391981/102174951-87c29b00-3e6c-11eb-9533-dd65fcf985a7.png)

**Comment by georgehelman** [comment]
@copelco Can you upload an example of when the checkmark should be checked?

**Comment by robert-w-gries** [comment]
Per Jessica (more info + examples in email):

> Form 287 has space for 10+ dismissed charges. If you are petitioning to expunge multiple dismissals, you check 1 of 2 boxes under Paragraph 3.

> The first is 3a: “I was charged with multiple offenses, and all of the charges were dismissed. I therefore am requesting the expunction of all the charges.”

> The second is 3b: “I was charged with multiple offenses, and while the charges listed above were dismissed, the following charges resulted in a conviction on the day of the dismissal or had not yet reached final disposition: (insert file no.(s) and offense description(s) of charges that were not dismissed). I therefore am requesting the expunction only of the dismissed charges listed above, and not all of the charges.”

> We have interpreted Paragraph 3b to implicate when a file number contains multiple charges and at least one did not lead to dismissal (i.e., was a conviction or has not yet been disposed). We need to include the file number and offense description of any count that did not result in dismissal in the box provided in Paragraph 3b.

**Comment by robert-w-gries** [comment]
Resolved by #371
