### ISSUE TITLE
CR and CRS offense records must be included on separate petitions

### ISSUE THREAD

**Issue by copelco** [deardurham/dear-petition#20]
Petitions must be specific to district or superior courts. If a batch contains both CR and CRS records, then they must be entered into separate petition forms with the appropriate box checked.

**Comment by copelco** [comment]
Both records work for viewing in-browser on:
* Mac + Chrome
* Windows 7 + Chrome

However, @georgehelman reports he still can't see the checkbox:

> This still doesn't work for me. Neither checkbox is checked in the download. If I save that download as a non-readable PDF, then both checkboxes are checked.

**Comment by copelco** [comment]
Joseph mentioned using Firefox, so I also confirmed fields + checkbox are filled on Windows 7 + Firefox. However, they're not editable in FF.

**Comment by georgehelman** [comment]
Behaviour seems to vary by browser and what you are trying to do with it, but not by OS.

Mac Chrome preview: Correct
Mac Chrome save as PDF: Missing checkbox
Mac Chrome download: Missing checkbox
Mac Firefox preview: Correct
Mac Firefox save as PDF: Missing everything but checkbox
Mac Firefox download: Missing checkbox
Windows Chrome preview: Correct
Windows Chrome save as PDF: Missing checkbox
Windows Chrome download: Missing checkbox
Windows Firefox preview: Correct
Windows Firefox save as PDF: Everything but checkbox
Windows Firefox download: Missing checkbox

**Comment by copelco** [comment]
To test, we need a CIPRS record that:

- Contains offenses that would populate a DISMISSED petition
- Is in a superior court jurisdiction

**Comment by copelco** [comment]
@georgehelman Can you upload these?
