### ISSUE TITLE
"OPEN CONT AFTER CONS ALC 1ST (Blood Alcohol = NOT REQUIRED)" not included on petition

### ISSUE THREAD

**Issue by georgehelman** [deardurham/dear-petition#215]
This record is in in Jessica's latest email. The person's initials are TS.

**Comment by copelco** [comment]
Possibly fixed by deardurham/ciprs-reader#41

**Comment by georgehelman** [comment]
This is happening because the the offense description continues to the next line which confuses the line parser.

**Comment by robert-w-gries** [comment]
Fixed by #282
