### ISSUE TITLE
Populate offense section in PDF

### ISSUE THREAD

**Issue by copelco** [deardurham/dear-petition#22]
Each row in the Petition PDF's offense section is keyed off of an incrementing index with these field names:
* File No.(s): ``Fileno:1``
* Date of Arrest: ``ArrestDate:1``
* Offense Description: ``Description:1``
* Date of Offense: ``DOOF:1``
* Disposition: ``Disposition:1``
* Date of Disposition: ``DispositionDate:1``

For each ``record.data["Offense Record"]["Records"]``, map:

- [x] File No: ``record.file_no`` -> ``Fileno:N``
- [x] Date of Arrest: ``record.offense_date`` -> ``ArrestDate:N``
- [x] Offense Description: ``record.data["Offense Record"]["Records"][N]["Description"]`` -> ``Description:N``
- [x] Date of Offense: ``record.offense_date`` -> ``DOOF:N``
- [x] Disposition: ``record.disposition_method`` -> ``Disposition:N``
- [x] Date of Disposition: ``record.disposed_on`` -> ``DispositionDate:N``

**Comment by georgehelman** [comment]
Intermittently deployed, but still need clarification from DEAR team on what to do about the disposition column, which overflows with the value "DISPOSED BY JUDGE"

**Comment by copelco** [comment]
Fixed in #27

**Comment by copelco** [comment]
Also fixed in #31

**Comment by georgehelman** [comment]
Work continued in https://github.com/deardurham/ciprs-reader/issues/10
