### ISSUE TITLE
Investigate email listener for CIPRS records

### ISSUE THREAD

**Issue by robert-w-gries** [deardurham/dear-petition#269]
Current process of how Jessica gets court records:

1. select up to 10 documents and send
1. Submit an email in the court record system
    *  need to deselect and then select 10 more to send another batch
    *  Design issue: how to validate that all the documents are for one person?
1. Jessica likes to compile the multiple documents into one pdf where it makes sense
    *  this seems like a difficult problem for us to tackle

**Comment by copelco** [comment]
Closed in #305
