### ISSUE TITLE
Offense record selector display bug

### ISSUE THREAD

**Issue by georgehelman** [deardurham/dear-petition#288]
One petition's offense record selector highlighting can change based on whether or not another one is open or closed
![Screenshot Capture - 2022-03-05 - 13-23-29](https://user-images.githubusercontent.com/43391981/156895622-598a86a0-d230-4270-b79b-11dccb834d32.png)
![Screenshot Capture - 2022-03-05 - 13-23-43](https://user-images.githubusercontent.com/43391981/156895624-489f5661-af43-45f1-b364-b1cbea2474e0.png)

**Comment by georgehelman** [comment]
Will probably be solved with Rob's frontend change to move offense record selector to modal.

**Comment by robert-w-gries** [comment]
Was resolved by recent changes to make offense table into a modal
