### ISSUE TITLE
Get rid of generate petition modal

### ISSUE THREAD

**Issue by georgehelman** [deardurham/dear-petition#316]
With the agency selection made a part of the document generation process, the modal no longer has an necessary information or functionality. Clicking on the petition in the generate petition page should go straight to generating the modal.

**Comment by robert-w-gries** [comment]
We can create an option to select certain page(s) of the main document + attachments to download/print.

Additionally, make an option to "preview" by opening pdf locally. Make an option to "download" by just downloading the file without opening pdf tab.

Maybe combine Petition and Attachments into "Petition Documents"
