### ISSUE TITLE
Arresting Agencies associated with counties

### ISSUE THREAD

**Issue by robert-w-gries** [deardurham/dear-petition#341]
Tl;dr it will automatically select arresting agencies for certain counties

Jessica info:

> As discussed in this morning’s call, please find attached the DEAR Cheat Sheet. The focus is on the sheet called “Arresting Agencies.” There, you’ll find a list of the arresting agencies we’ve identified, broken down by county.
 
> To use it, a person looks to the county in which the target charge arose, then identifies which arresting agency is relevant. If the matter relates to State Highway Patrol (SHP), you’ll see under a troop identified in the county name. Then you scroll to the bottom, “State Highway Patrol,” and find the Troop Headquarters and Division number for the address(es) to include.

> Example 1: Client has dismissed charge from Pender County, charged by Surf City Police Department. Under “Pender,” you’ll find Surf City PD’s address. On the expunction petition, include 2 addresses: Surf City PD, and Pender County Sheriff’s Department. (Always include sheriff’s department)

> Example 1: Client has dismissed charge from Pender County by SHP. Under “Pender,” you see that’s Troop B. Under Troop B, you’ll see that’s District IV. On the expunction petition, include 4 addresses: SHP Headquarters, SHP Troop B Headquarters, SHP Troop B, Division IV, and Pender County Sheriff’s Department. (Always include sheriff’s department.)

**Comment by georgehelman** [comment]
I think we have this covered now. Agencies have associated counties, and sheriff's offices always get added now.
