### ISSUE TITLE
Add sheriff as arresting agency to each petition

### ISSUE THREAD

**Issue by austin-bagwell** [deardurham/dear-petition#410]
Each County has only one sheriff. List of arresting agencies, including sheriff's departments, to be provided by Legal Aid team

- Priority is adding the sheriff department to every county
- Jessica always puts the sheriff department as the first arresting agency, other police departments follow
- Sheriff should be on every petition, always be first

**Comment by georgehelman** [comment]
We did this in this PR: https://github.com/deardurham/dear-petition/pull/448
