### ISSUE TITLE
Import portal records

### ISSUE THREAD

**Issue by copelco** [deardurham/dear-petition#440]

**Comment by robert-w-gries** [comment]
Where we're at

* bookmarklet basic functionality working where it sends the HTML data of the record to the server
* We embed the username into the bookmarklet so it's associated with the user automatically
* The record appears in the user's dashboard

What needs work:

* supporting parsing of entire portal HTML doc into matching format of ciprs-reader
* the bookmarklet could provide better feedback of whether sending record succeeded or failed
* investigate whether embedding more user/metadata into bookmarklet would help
