### ISSUE TITLE
Duplicate charges from conviction and dismissal

### ISSUE THREAD

**Issue by rebecca-draben** [deardurham/dear-petition#463]
From Emily in Oct 20, 2023 email: "Now I’m going to send examples of records when the person was convicted in District Court but appeals it to Superior Court where the charges are dismissed. I’ve attached two records with this situation. When we ran it through the Pet Gen Tool, it registered both the conviction and the dismissals under the same case number, making it appear as if there were twice as many charges as there are."

(see email for specific examples)

**Comment by georgehelman** [comment]
We have handled this. This is the superseding indictment scenario.
