### ISSUE TITLE
Include new Portal record(s) in existing petition

### ISSUE THREAD

**Issue by rebecca-draben** [deardurham/dear-petition#469]
As an expunction attorney, when I add Portal records, I would like to add them to an existing petition for so that the record(s) will all appear on the same record summary.

AC:
* Show prompt to enter batch label when using Portal bookmarklet

**Comment by georgehelman** [comment]
I was thinking another possible approach would be to add a way to combine batches on the Existing Petitions section on the landing page. One possible shortcoming of the approach of inputting a label in the Portal bookmarklet is that it is assuming the CIPRS imported batch already exists. This means they always have to import the CIPRS record before the Portal record and can't do it the other way around. We could keep the two import processes as is and add a third process to combine.

**Comment by georgehelman** [comment]
We added the ability to combine records
