### ISSUE TITLE
Use full address of DEAR Office in Name and Address of Petitioner's Attorney field

### ISSUE THREAD

**Issue by georgehelman** [deardurham/dear-petition#48]
510 South Dillard Street, Durham, NC 27701

**Comment by copelco** [comment]
Attorney and agencies are now managed by the admins on the site.

**Comment by borncrispy** [comment]
Should this be managed by the admin or should there be a default address if one is not provided?

**Comment by borncrispy** [comment]
@copelco Seems like managing the address through the admin panel and not at the code level would make this a more user friendly product. Unless I'm missing something.

**Comment by copelco** [comment]
Correct @borncrispy -- this is already managed through the admin! Thank you.
