### ISSUE TITLE
Change file naming convention for generated Petitions and Account Summary

### ISSUE THREAD

**Issue by robert-w-gries** [deardurham/dear-petition#481]
## Petition

LANC has adopted a new file naming convention (YEAR-MONTH-DAY DOCUMENT TYPE Client Name). We have a request to change the file names generated by the robot.

Currently, petition file names: CLIENTNAME FORMNUMBER DISTRICT/SUPERIOR COUNTY

We request instead: DATEGENERATED COUNTY DISTRICT/SUPERIOR FORM-STATUTE CLIENTNAME

We’re asking to change from form number to statute number, because the forms may change but the statutes are less likely to change.

Therefore:

![image](https://github.com/deardurham/dear-petition/assets/7546625/15f1db17-bd2f-4264-b04f-c440bc585484)

As an example:

Current: John Doe AOC-CR-287 D Lee

New: 2024-05-15 Lee SC 287 John Doe

## Account Summary

For case summaries, let’s re-name to the following:

DATEGENERATED Record Summary CLIENTNAME

**Comment by georgehelman** [comment]
Instead of 287, the New format should use statute number.

146 = DISMISSALS
145.5F = FELONY CONVICTIONS
145.5M - MISDEMEANOR CONVICTIONS
145.8A - YOUTHFUL CONVICTIONS

**Comment by georgehelman** [comment]
We did this here: https://github.com/deardurham/dear-petition/commit/20e77fd5c391d38a44ae83f445833008e8e4fa68
