### ISSUE TITLE
Open to other developers?

### ISSUE THREAD

**Issue by gogingersnap777** [deardurham/dear-petition#482]
I live in Fuquay Varina,NC and just came across Code with Durham!

I work for Cisco, but I'm working on open source development in my off time. I know Python/Go the best, but I am able to catch onto anything pretty quick.

Are the issues in this repo open to work on?

**Comment by zachajon-cisco** [comment]
I asked the same question in the discord!

**Comment by gogingersnap777** [comment]
Asked the same question in discord! Closing this issue
