### ISSUE TITLE
Upgrade Redis on stage and prod

### ISSUE THREAD

**Issue by rebecca-draben** [deardurham/dear-petition#493]
Email from Heroku (this is for prod, but similar notification for stage):

Running up-to-date software versions is essential for maintaining a highly-available and secure fleet of Heroku Data for Redis instances.

Your Redis database redis-cubed-72412 on dear-petition is running a [deprecated version](https://devcenter.heroku.com/articles/heroku-redis#version-support-and-legacy-infrastructure) (6.2.14) and will not be supported after 02 Dec, 2024.

We urge you to upgrade to version 7.2 as we’re disallowing provisioning of the deprecated version from 02 Oct, 2024. If no action is taken, then we’ll perform forced upgrades after 31 Oct, 2024.

We perform heavy testing and validation work on all our Redis releases, including testing the upgrade procedure, and are careful to only recommend versions that we trust.

You can upgrade your Redis database to the latest default version by using heroku redis:upgrade command. You can read more about this procedure in our [Dev Center article](https://devcenter.heroku.com/articles/heroku-redis-version-upgrade).

**Comment by georgehelman** [comment]
Rob upgraded with command `heroku redis:upgrade redis-cubic-30055 --version 7.2.6 --app dear-petition-staging`
